version: "3.9"
   
services:
  db:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
     - DB_HOST=db
     - DB_NAME=postgres
     - DB_USER=postgres
     - DB_PASS=postgres
    command: >
      sh -c "python manage.py wait_for_db & python manage.py migrate & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: "redis"
  celery:
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    build: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis